version = 1

[[annotations]]
path = "AUTHORS"
SPDX-FileCopyrightText = [
    "2025 Monaco F. J. <monaco@usp.br>",
    "2025 Silva F. F. <fernandoferreira.silva42@usp.br>"
]
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "examples/*.ipynb"
SPDX-FileCopyrightText = [
    "2025 Monaco F. J. <monaco@usp.br>",
    "2025 Silva F. F. <fernandoferreira.silva42@usp.br>"
]
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "examples/__pycache__/*"
SPDX-FileCopyrightText = [
    "2025 Monaco F. J. <monaco@usp.br>",
    "2025 Silva F. F. <fernandoferreira.silva42@usp.br>"
]
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "MoeaBench/stats/__pycache__/*"
SPDX-FileCopyrightText = [
    "2025 Monaco F. J. <monaco@usp.br>",
    "2025 Silva F. F. <fernandoferreira.silva42@usp.br>"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
